name: skb-lab

volumes:
  db:

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-skb}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-user}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
